
//
// colors/iOS/colors.swift
//

// Do not edit directly
// Generated on Fri, 25 Nov 2022 08:15:48 GMT


import SwiftUI

public enum MeisterColors {
    public static let mdsColorOpacityW95 = #fffffff2
    public static let mdsColorOpacityW80 = #ffffffcc
    public static let mdsColorOpacityW75 = #ffffffbf
    public static let mdsColorOpacityW50 = #ffffff80
    public static let mdsColorOpacityW30 = #ffffff4d
    public static let mdsColorOpacityW20 = #ffffff33
    public static let mdsColorOpacityW10 = #ffffff1a
    public static let mdsColorOpacityB50 = #29303380
    public static let mdsColorOpacityB30 = #2930334d
    public static let mdsColorOpacityB20 = #29303333
    public static let mdsColorOpacityB10 = #2930331a
    public static let mdsColorOpacityB05 = #2930330d
    public static let mdsColorOpacityB03 = #29303308
    public static let mdsColorGreyGrey1000 = #000000
    public static let mdsColorGreyGrey900 = #293033
    public static let mdsColorGreyGrey800 = #333c40
    public static let mdsColorGreyGrey700 = #3d474d
    public static let mdsColorGreyGrey600 = #626d73
    public static let mdsColorGreyGrey500 = #8a9499
    public static let mdsColorGreyGrey400 = #b6bdc0
    public static let mdsColorGreyGrey300 = #e1e4e6
    public static let mdsColorGreyGrey200 = #f0f1f2
    public static let mdsColorGreyGrey100 = #f7f7f7
    public static let mdsColorGreyGrey000 = #ffffff
    public static let mdsColorPurplePurple900 = #401a66
    public static let mdsColorPurplePurple800 = #5f2b9a
    public static let mdsColorPurplePurple700 = #7840c5
    public static let mdsColorPurplePurple600 = #8d5ae2
    public static let mdsColorPurplePurple500 = #a179f2
    public static let mdsColorPurplePurple400 = #bb9bfa
    public static let mdsColorPurplePurple300 = #caaefc
    public static let mdsColorPurplePurple200 = #d9c2fd
    public static let mdsColorPurplePurple100 = #e7d8fe
    public static let mdsColorPurplePurple000 = #f5edff
    public static let mdsColorPinkPink900 = #4d1720
    public static let mdsColorPinkPink800 = #772233
    public static let mdsColorPinkPink700 = #a22e49
    public static let mdsColorPinkPink600 = #cc3e66
    public static let mdsColorPinkPink500 = #f7578c
    public static let mdsColorPinkPink400 = #ff80ad
    public static let mdsColorPinkPink300 = #ff9abd
    public static let mdsColorPinkPink200 = #ffb4ce
    public static let mdsColorPinkPink100 = #ffcfe0
    public static let mdsColorPinkPink000 = #ffebf1
    public static let mdsColorRedRed900 = #5c1f16
    public static let mdsColorRedRed800 = #85271b
    public static let mdsColorRedRed700 = #a72f1f
    public static let mdsColorRedRed600 = #d42d20
    public static let mdsColorRedRed500 = #e94235
    public static let mdsColorRedRed400 = #f46054
    public static let mdsColorRedRed300 = #f77f73
    public static let mdsColorRedRed200 = #fa9e95
    public static let mdsColorRedRed100 = #fbc2ba
    public static let mdsColorRedRed000 = #fbe8e5
    public static let mdsColorOrangeOrange900 = #593109
    public static let mdsColorOrangeOrange800 = #834905
    public static let mdsColorOrangeOrange700 = #ac6400
    public static let mdsColorOrangeOrange600 = #d68500
    public static let mdsColorOrangeOrange500 = #ffaa00
    public static let mdsColorOrangeOrange400 = #ffbc39
    public static let mdsColorOrangeOrange300 = #ffc563
    public static let mdsColorOrangeOrange200 = #ffd08c
    public static let mdsColorOrangeOrange100 = #ffdfb7
    public static let mdsColorOrangeOrange000 = #fff0e1
    public static let mdsColorYellowYellow900 = #7c5701
    public static let mdsColorYellowYellow800 = #aa7b00
    public static let mdsColorYellowYellow700 = #dfa304
    public static let mdsColorYellowYellow600 = #f4bb10
    public static let mdsColorYellowYellow500 = #ffd426
    public static let mdsColorYellowYellow400 = #ffe062
    public static let mdsColorYellowYellow300 = #ffe578
    public static let mdsColorYellowYellow200 = #ffea8f
    public static let mdsColorYellowYellow100 = #fff2b3
    public static let mdsColorYellowYellow000 = #fff8d7
    public static let mdsColorGreenGreen900 = #0c3b22
    public static let mdsColorGreenGreen800 = #125f2f
    public static let mdsColorGreenGreen700 = #1a8335
    public static let mdsColorGreenGreen600 = #27a838
    public static let mdsColorGreenGreen500 = #3dcc3d
    public static let mdsColorGreenGreen400 = #67e16e
    public static let mdsColorGreenGreen300 = #85e990
    public static let mdsColorGreenGreen200 = #a3f0b1
    public static let mdsColorGreenGreen100 = #c6f8d2
    public static let mdsColorGreenGreen000 = #ebfff1
    public static let mdsColorGrassGrass900 = #273d11
    public static let mdsColorGrassGrass800 = #3f6513
    public static let mdsColorGrassGrass700 = #578c11
    public static let mdsColorGrassGrass600 = #74b40d
    public static let mdsColorGrassGrass500 = #96db0b
    public static let mdsColorGrassGrass400 = #b3ed39
    public static let mdsColorGrassGrass300 = #c1f25e
    public static let mdsColorGrassGrass200 = #d0f684
    public static let mdsColorGrassGrass100 = #e1fbae
    public static let mdsColorGrassGrass000 = #f2ffd9
    public static let mdsColorCyanCyan900 = #004249
    public static let mdsColorCyanCyan800 = #006570
    public static let mdsColorCyanCyan700 = #0d8d93
    public static let mdsColorCyanCyan600 = #1cb6b8
    public static let mdsColorCyanCyan500 = #2ed7d8
    public static let mdsColorCyanCyan400 = #61eae3
    public static let mdsColorCyanCyan300 = #81efe6
    public static let mdsColorCyanCyan200 = #a3f4ec
    public static let mdsColorCyanCyan100 = #c1f9f1
    public static let mdsColorCyanCyan000 = #e0fef9
    public static let mdsColorBlueBlue900 = #003459
    public static let mdsColorBlueBlue800 = #005186
    public static let mdsColorBlueBlue700 = #0071b5
    public static let mdsColorBlueBlue600 = #008fdf
    public static let mdsColorBlueBlue500 = #00aa11
    public static let mdsColorBlueBlue400 = #30c0ff
    public static let mdsColorBlueBlue300 = #58ccff
    public static let mdsColorBlueBlue200 = #81d8ff
    public static let mdsColorBlueBlue100 = #b4e8ff
    public static let mdsColorBlueBlue000 = #e6f7ff
    public static let mdsColorNavyNavy900 = #002259
    public static let mdsColorNavyNavy800 = #083283
    public static let mdsColorNavyNavy700 = #1644ac
    public static let mdsColorNavyNavy600 = #2858d6
    public static let mdsColorNavyNavy500 = #4070ff
    public static let mdsColorNavyNavy400 = #5c93ff
    public static let mdsColorNavyNavy300 = #7cb0ff
    public static let mdsColorNavyNavy200 = #9cc9ff
    public static let mdsColorNavyNavy100 = #bfe0ff
    public static let mdsColorNavyNavy000 = #e2f2ff
    public static let mdsMdsSpacingXs = 8
    public static let mdsMdsMetadataTokenSetOrder2 = fontStyle
    public static let mdsMdsMetadataTokenSetOrder1 = webfont
    public static let mdsMdsMetadataTokenSetOrder0 = colors
    public static let mdsMdsWebfontTextDecorationUnderline = underline
    public static let mdsMdsWebfontTextDecorationNone = none
    public static let mdsMdsWebfontTextCaseNone = none
    public static let mdsMdsWebfontParagraphSpacingNormal = 0
    public static let mdsMdsWebfontLetterSpacingSmaller = -1.5%
    public static let mdsMdsWebfontLetterSpacingSmall = -1%
    public static let mdsMdsWebfontLetterSpacingNormal = 0%
    public static let mdsMdsWebfontFontSizeXxxl = 60
    public static let mdsMdsWebfontFontSizeXxl = 34
    public static let mdsMdsWebfontFontSizeXl = 21
    public static let mdsMdsWebfontFontSizeL = 17
    public static let mdsMdsWebfontFontSizeM = 15
    public static let mdsMdsWebfontFontSizeS = 13
    public static let mdsMdsWebfontFontSizeXs = 11
    public static let mdsMdsWebfontFontWeightBold = 700
    public static let mdsMdsWebfontFontWeightMedium = 500
    public static let mdsMdsWebfontFontWeightRegular = 400
    public static let mdsMdsWebfontLineHeightXxxl = 70
    public static let mdsMdsWebfontLineHeightXxl = 44
    public static let mdsMdsWebfontLineHeightXl = 31
    public static let mdsMdsWebfontLineHeightL = 25
    public static let mdsMdsWebfontLineHeightM = 22
    public static let mdsMdsWebfontLineHeightS = 18
    public static let mdsMdsWebfontLineHeightXs = 17
    public static let mdsMdsWebfontFontFamilyWeb = Avenir
    public static let mdsMdsColorsOpacityW95 = #fffffff2
    public static let mdsMdsColorsOpacityW80 = #ffffffcc
    public static let mdsMdsColorsOpacityW75 = #ffffffbf
    public static let mdsMdsColorsOpacityW50 = #ffffff80
    public static let mdsMdsColorsOpacityW30 = #ffffff4d
    public static let mdsMdsColorsOpacityW20 = #ffffff33
    public static let mdsMdsColorsOpacityW10 = #ffffff1a
    public static let mdsMdsColorsOpacityB50 = #29303380
    public static let mdsMdsColorsOpacityB30 = #2930334d
    public static let mdsMdsColorsOpacityB20 = #29303333
    public static let mdsMdsColorsOpacityB10 = #2930331a
    public static let mdsMdsColorsOpacityB05 = #2930330d
    public static let mdsMdsColorsOpacityB03 = #29303308
    public static let mdsMdsColorsGreyGrey1000 = #000000
    public static let mdsMdsColorsGreyGrey900 = #293033
    public static let mdsMdsColorsGreyGrey800 = #333c40
    public static let mdsMdsColorsGreyGrey700 = #3d474d
    public static let mdsMdsColorsGreyGrey600 = #626d73
    public static let mdsMdsColorsGreyGrey500 = #8a9499
    public static let mdsMdsColorsGreyGrey400 = #b6bdc0
    public static let mdsMdsColorsGreyGrey300 = #e1e4e6
    public static let mdsMdsColorsGreyGrey200 = #f0f1f2
    public static let mdsMdsColorsGreyGrey100 = #f7f7f7
    public static let mdsMdsColorsGreyGrey000 = #ffffff
    public static let mdsMdsColorsPurplePurple900 = #401a66
    public static let mdsMdsColorsPurplePurple800 = #5f2b9a
    public static let mdsMdsColorsPurplePurple700 = #7840c5
    public static let mdsMdsColorsPurplePurple600 = #8d5ae2
    public static let mdsMdsColorsPurplePurple500 = #a179f2
    public static let mdsMdsColorsPurplePurple400 = #bb9bfa
    public static let mdsMdsColorsPurplePurple300 = #caaefc
    public static let mdsMdsColorsPurplePurple200 = #d9c2fd
    public static let mdsMdsColorsPurplePurple100 = #e7d8fe
    public static let mdsMdsColorsPurplePurple000 = #f5edff
    public static let mdsMdsColorsPinkPink900 = #4d1720
    public static let mdsMdsColorsPinkPink800 = #772233
    public static let mdsMdsColorsPinkPink700 = #a22e49
    public static let mdsMdsColorsPinkPink600 = #cc3e66
    public static let mdsMdsColorsPinkPink500 = #f7578c
    public static let mdsMdsColorsPinkPink400 = #ff80ad
    public static let mdsMdsColorsPinkPink300 = #ff9abd
    public static let mdsMdsColorsPinkPink200 = #ffb4ce
    public static let mdsMdsColorsPinkPink100 = #ffcfe0
    public static let mdsMdsColorsPinkPink000 = #ffebf1
    public static let mdsMdsColorsRedRed900 = #5c1f16
    public static let mdsMdsColorsRedRed800 = #85271b
    public static let mdsMdsColorsRedRed700 = #a72f1f
    public static let mdsMdsColorsRedRed600 = #d42d20
    public static let mdsMdsColorsRedRed500 = #e94235
    public static let mdsMdsColorsRedRed400 = #f46054
    public static let mdsMdsColorsRedRed300 = #f77f73
    public static let mdsMdsColorsRedRed200 = #fa9e95
    public static let mdsMdsColorsRedRed100 = #fbc2ba
    public static let mdsMdsColorsRedRed000 = #fbe8e5
    public static let mdsMdsColorsOrangeOrange900 = #593109
    public static let mdsMdsColorsOrangeOrange800 = #834905
    public static let mdsMdsColorsOrangeOrange700 = #ac6400
    public static let mdsMdsColorsOrangeOrange600 = #d68500
    public static let mdsMdsColorsOrangeOrange500 = #ffaa00
    public static let mdsMdsColorsOrangeOrange400 = #ffbc39
    public static let mdsMdsColorsOrangeOrange300 = #ffc563
    public static let mdsMdsColorsOrangeOrange200 = #ffd08c
    public static let mdsMdsColorsOrangeOrange100 = #ffdfb7
    public static let mdsMdsColorsOrangeOrange000 = #fff0e1
    public static let mdsMdsColorsYellowYellow900 = #7c5701
    public static let mdsMdsColorsYellowYellow800 = #aa7b00
    public static let mdsMdsColorsYellowYellow700 = #dfa304
    public static let mdsMdsColorsYellowYellow600 = #f4bb10
    public static let mdsMdsColorsYellowYellow500 = #ffd426
    public static let mdsMdsColorsYellowYellow400 = #ffe062
    public static let mdsMdsColorsYellowYellow300 = #ffe578
    public static let mdsMdsColorsYellowYellow200 = #ffea8f
    public static let mdsMdsColorsYellowYellow100 = #fff2b3
    public static let mdsMdsColorsYellowYellow000 = #fff8d7
    public static let mdsMdsColorsGreenGreen900 = #0c3b22
    public static let mdsMdsColorsGreenGreen800 = #125f2f
    public static let mdsMdsColorsGreenGreen700 = #1a8335
    public static let mdsMdsColorsGreenGreen600 = #27a838
    public static let mdsMdsColorsGreenGreen500 = #3dcc3d
    public static let mdsMdsColorsGreenGreen400 = #67e16e
    public static let mdsMdsColorsGreenGreen300 = #85e990
    public static let mdsMdsColorsGreenGreen200 = #a3f0b1
    public static let mdsMdsColorsGreenGreen100 = #c6f8d2
    public static let mdsMdsColorsGreenGreen000 = #ebfff1
    public static let mdsMdsColorsGrassGrass900 = #273d11
    public static let mdsMdsColorsGrassGrass800 = #3f6513
    public static let mdsMdsColorsGrassGrass700 = #578c11
    public static let mdsMdsColorsGrassGrass600 = #74b40d
    public static let mdsMdsColorsGrassGrass500 = #96db0b
    public static let mdsMdsColorsGrassGrass400 = #b3ed39
    public static let mdsMdsColorsGrassGrass300 = #c1f25e
    public static let mdsMdsColorsGrassGrass200 = #d0f684
    public static let mdsMdsColorsGrassGrass100 = #e1fbae
    public static let mdsMdsColorsGrassGrass000 = #f2ffd9
    public static let mdsMdsColorsCyanCyan900 = #004249
    public static let mdsMdsColorsCyanCyan800 = #006570
    public static let mdsMdsColorsCyanCyan700 = #0d8d93
    public static let mdsMdsColorsCyanCyan600 = #1cb6b8
    public static let mdsMdsColorsCyanCyan500 = #2ed7d8
    public static let mdsMdsColorsCyanCyan400 = #61eae3
    public static let mdsMdsColorsCyanCyan300 = #81efe6
    public static let mdsMdsColorsCyanCyan200 = #a3f4ec
    public static let mdsMdsColorsCyanCyan100 = #c1f9f1
    public static let mdsMdsColorsCyanCyan000 = #e0fef9
    public static let mdsMdsColorsBlueBlue900 = #003459
    public static let mdsMdsColorsBlueBlue800 = #005186
    public static let mdsMdsColorsBlueBlue700 = #0071b5
    public static let mdsMdsColorsBlueBlue600 = #008fdf
    public static let mdsMdsColorsBlueBlue500 = #00aa11
    public static let mdsMdsColorsBlueBlue400 = #30c0ff
    public static let mdsMdsColorsBlueBlue300 = #58ccff
    public static let mdsMdsColorsBlueBlue200 = #81d8ff
    public static let mdsMdsColorsBlueBlue100 = #b4e8ff
    public static let mdsMdsColorsBlueBlue000 = #e6f7ff
    public static let mdsMdsColorsNavyNavy900 = #002259
    public static let mdsMdsColorsNavyNavy800 = #083283
    public static let mdsMdsColorsNavyNavy700 = #1644ac
    public static let mdsMdsColorsNavyNavy600 = #2858d6
    public static let mdsMdsColorsNavyNavy500 = #4070ff
    public static let mdsMdsColorsNavyNavy400 = #5c93ff
    public static let mdsMdsColorsNavyNavy300 = #7cb0ff
    public static let mdsMdsColorsNavyNavy200 = #9cc9ff
    public static let mdsMdsColorsNavyNavy100 = #bfe0ff
    public static let mdsMdsColorsNavyNavy000 = #e2f2ff
    public static let mdsColorDefaultWhite = mdsColorGreyGrey000
    public static let mdsColorDefaultBlack = mdsColorGreyGrey1000
    public static let mdsColorDefaultPurple = mdsColorPurplePurple500
    public static let mdsColorDefaultPink = mdsColorPinkPink500
    public static let mdsColorDefaultRed = mdsColorRedRed600
    public static let mdsColorDefaultOrange = mdsColorOrangeOrange500
    public static let mdsColorDefaultYellow = mdsColorYellowYellow500
    public static let mdsColorDefaultGreen = mdsColorGreenGreen500
    public static let mdsColorDefaultGrass = mdsColorGrassGrass500
    public static let mdsColorDefaultCyan = mdsColorCyanCyan500
    public static let mdsColorDefaultNavy = mdsColorNavyNavy500
    public static let mdsColorDefaultBlue = mdsColorBlueBlue500
    public static let mdsColorDefaultBanana = mdsColorYellowYellow100
    public static let mdsColorDefaultSky = mdsColorBlueBlue000
    public static let mdsMdsSpacingXxxl = calc(mdsMdsSpacingXs*7)
    public static let mdsMdsSpacingXxl = calc(mdsMdsSpacingXs*6)
    public static let mdsMdsSpacingXl = calc(mdsMdsSpacingXs*5)
    public static let mdsMdsSpacingL = calc(mdsMdsSpacingXs*4)
    public static let mdsMdsSpacingM = calc(mdsMdsSpacingXs*3)
    public static let mdsMdsSpacingS = calc(mdsMdsSpacingXs*2)
    public static let mdsMdsFontStyle07xxxlBold = [object Object]
    public static let mdsMdsFontStyle07xxxlMedium = [object Object]
    public static let mdsMdsFontStyle07xxxlRegular = [object Object]
    public static let mdsMdsFontStyle06xxlBold = [object Object]
    public static let mdsMdsFontStyle06xxlMedium = [object Object]
    public static let mdsMdsFontStyle06xxlRegular = [object Object]
    public static let mdsMdsFontStyle05xlBold = [object Object]
    public static let mdsMdsFontStyle05xlMedium = [object Object]
    public static let mdsMdsFontStyle05xlRegular = [object Object]
    public static let mdsMdsFontStyle04lLink = [object Object]
    public static let mdsMdsFontStyle04lBold = [object Object]
    public static let mdsMdsFontStyle04lMedium = [object Object]
    public static let mdsMdsFontStyle04lRegular = [object Object]
    public static let mdsMdsFontStyle03mLink = [object Object]
    public static let mdsMdsFontStyle03mBold = [object Object]
    public static let mdsMdsFontStyle03mMedium = [object Object]
    public static let mdsMdsFontStyle03mRegular = [object Object]
    public static let mdsMdsFontStyle02sLink = [object Object]
    public static let mdsMdsFontStyle02sBold = [object Object]
    public static let mdsMdsFontStyle02sMedium = [object Object]
    public static let mdsMdsFontStyle02sRegular = [object Object]
    public static let mdsMdsFontStyle01xsBold = [object Object]
    public static let mdsMdsFontStyle01xsMedium = [object Object]
    public static let mdsMdsFontStyle01xsRegular = [object Object]
    public static let mdsMdsColorsDefaultWhite = mdsMdsColorsGreyGrey000
    public static let mdsMdsColorsDefaultBlack = mdsMdsColorsGreyGrey1000
    public static let mdsMdsColorsDefaultPurple = mdsMdsColorsPurplePurple500
    public static let mdsMdsColorsDefaultPink = mdsMdsColorsPinkPink500
    public static let mdsMdsColorsDefaultRed = mdsMdsColorsRedRed600
    public static let mdsMdsColorsDefaultOrange = mdsMdsColorsOrangeOrange500
    public static let mdsMdsColorsDefaultYellow = mdsMdsColorsYellowYellow500
    public static let mdsMdsColorsDefaultGreen = mdsMdsColorsGreenGreen500
    public static let mdsMdsColorsDefaultGrass = mdsMdsColorsGrassGrass500
    public static let mdsMdsColorsDefaultCyan = mdsMdsColorsCyanCyan500
    public static let mdsMdsColorsDefaultNavy = mdsMdsColorsNavyNavy500
    public static let mdsMdsColorsDefaultBlue = mdsMdsColorsBlueBlue500
    public static let mdsMdsColorsDefaultBanana = mdsMdsColorsYellowYellow100
    public static let mdsMdsColorsDefaultSky = mdsMdsColorsBlueBlue000
}
