name: Optimize SVGs
on:
  push:
    paths:
      - 'packages/foundations/icons/**' # Only trigger on SVGs folder
    branches-ignore:
      - master
jobs:
  svgs:
    name: SVGs
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip svgo]')"
    steps:
    - uses: actions/checkout@v3
    - uses: ericcornelissen/svgo-action@v3
      id: svgo
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        strict: true
        svgo-config: svgo.config.js
        ignore: packages/foundations/!(icons)/** # Ignore all folders except SVGs folder
        svgo-version: 3
    - name: Commit optimizations
      uses: stefanzweifel/git-auto-commit-action@v4
      if: ${{steps.svgo.outputs.DID_OPTIMIZE}}
      with:
        commit_message: Optimize ${{steps.svgo.outputs.OPTIMIZED_COUNT}} SVG(s)